### ISSUE TITLE
output should be absolute path

### ISSUE THREAD

**Issue by luandro** [ConservationMetrics/mbgl-tile-renderer#16]
## Current Buggy or Suspicious Behavior

```
const outputPath = `outputs/${output}.mbtiles`;
```

## Expected Behavior

`  const outputPath = output;`

**Comment by rudokemper** [comment]
Thanks! I actually just addressed this in [17](https://github.com/ConservationMetrics/mbgl-tile-renderer/pull/17), because I needed absolute path for the task worker service.
